### ISSUE TITLE
Usage Question

### ISSUE THREAD

**Issue by HDVinnie** [jeremykenedy/laravel2step#1]
This is a really neat package.....but from what Im understanding it replaces the default password login usage? I am thinking it would be neat if there was a added column to the users table called "twostep_auth". True or False / 0 or 1. If false then user logs in as normal with there username and password. If true then they login with username and password but then redirect to enter there twostep_auth code before getting full access and redirected to home page of ones site?

**Comment by jeremykenedy** [comment]
Currently, it does not take over the password and email login system. That's all still needed.

Its a middleware that intercepts those and then checks against the table.

I do plan on adding a column to allow the user to check that they want 2-step auth enabled. I also need to put in a handler system in place for then the user uses a system such as socialite and will not trigger if the auth is using that.

Thanks for checking out the project.
