### ISSUE TITLE
I may have missed it but

### ISSUE THREAD

**Issue by ghost** [jeremykenedy/laravel2step#15]
Hello. This isnt a bug but I may have missed it in the documentation somewhere or a route not specified.
I have it all working and its great but when my user logs out the record in the database for 2fa is not removed and if they immediately then log back in there is no request for 2fa. Is there a setting I am missing to force 2fa on every login regardless that they have just logged out.
Many thanks
Neil

**Comment by jeremykenedy** [comment]
https://github.com/jeremykenedy/laravel2step#usage

The package doesn’t do anything on logout. 

There is a check in place to see if they have verified in the last 6 hours. 

LARAVEL_2STEP_VERIFIED_LIFETIME_MINUTES=360
